# This workflow will build TourGuide Project project with Maven

name: Build, test and push image TourGuide Project PM to Docker hub

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test-push-image:

    runs-on: ubuntu-latest

    steps:
    - name: Get current TourGuide Project on master
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Add external jars to local maven repository
      run: |
       mvn install:install-file -Dfile="./TourGuide/libs/gpsUtil.jar" -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar
       mvn install:install-file -Dfile="./TourGuide/libs/RewardCentral.jar" -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar
       mvn install:install-file -Dfile="./TourGuide/libs/TripPricer.jar" -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar
    - name: Build with Maven
      run: mvn -B package spring-boot:repackage --file ./TourGuide/pom.xml
    - name: Print target folder content
      run: ls -a ./TourGuide/target
    - name: Print target folder content
      run: ls -a ./TourGuide/target 
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
       context: ./TourGuide
       push: true
       tags: tourguide-pm:latest
   

   
