# This workflow will build TourGuide Project project with Maven

name: Build, test and upload TourGuide Project PM

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test-upload:

    runs-on: ubuntu-latest

    steps:
    - name: Get current TourGuide Project on master
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Add external jars to local maven repository
      run: |
       mvn install:install-file -Dfile="./TourGuide/libs/gpsUtil.jar" -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar
       mvn install:install-file -Dfile="./TourGuide/libs/RewardCentral.jar" -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar
       mvn install:install-file -Dfile="./TourGuide/libs/TripPricer.jar" -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar
    - name: Build with Maven
      run: mvn -B package --file ./TourGuide/pom.xml
    - name: Print current directory with project files
      run: ls -a ./TourGuide
    - name: Print target folder content
      run: ls -a ./TourGuide/target
    - name: Create directory with jar and dockerfile to upload
      run: |
        mkdir tourguide-jar-dockerfile
        cp ./TourGuide/target/*.jar tourguide-jar-dockerfile
        cp ./TourGuide/Dockerfile tourguide-jar-dockerfile
        ls -a
    - name: Upload artifact with jar and docker file
      uses: actions/upload-artifact@v4
      with:
         name: tourguide-pm
         path: tourguide-jar-dockerfile

   
